### ISSUE TITLE
review todo list for #2813

### ISSUE THREAD

**Issue by iChenLei** [stylus/stylus#2814]
review todo list for #2813
- [ ] lib/cache/fs.js
- [ ] lib/cache/memory.js
- [ ] lib/cache/null.js
- [ ] lib/covert/css.js
- [ ] lib/errors.js
- [ ] lib/functions/image.js
- [ ] lib/lexer.js
- [ ] lib/nodes
- [ ] lib/parser.js
- [ ] lib/renderer.js
- [ ] lib/selector-parser.js
- [ ] lib/stack/frame.js
- [ ] lib/stack/index.js
- [ ] lib/stack/scope.js
- [ ] lib/token.js
- [ ] lib/visitor/compiler.js
- [ ] lib/visitor/deps-resolver.js
- [ ] lib/visitor/evaluator.js
- [ ] lib/visitor/index.js
- [ ] lib/visitor/normalizer.js
- [ ] lib/visitor/sourcemapper.js

**Comment by iChenLei** [comment]
<img width="560" alt="截屏2023-08-19 15 41 40" src="https://github.com/stylus/stylus/assets/14012511/083715f5-6e23-4392-ae49-53a995b65c62">

we can use the github builtin feature to review , so close it.
